config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # ルートパスへのアクセスがあったら、messages_controllerのindexアクションが呼び出される
  root to: "rooms#index"
  # ユーザー編集画面の表示へアクセスするための記述
  resources :users, only: [:edit, :update]
  # 新規チャットルームの作成で動くアクションは「new」と「create」
  # チャットルームの削除機能「destroy」を実装
  resources :rooms, only: [:new, :create, :destroy] do
    # どのルームで投稿されたメッセージなのかをパスから判断できるようにしたいので、ルーティングのネストを利用
    # メッセージに結びつくルームのidの情報を含んだパスを、受け取れるようになる
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  # 1つのメッセージは、1つのチャットルームに存在
  belongs_to :room
  # 1つのメッセージは、1人のユーザーから送信
  belongs_to :user
  # 各レコードとファイルを1対1の関係で紐づけるメソッド
  has_one_attached :image  
  # 「content」カラムに、presence: trueを設けることで、空の場合はDBに保存しないというバリデーションを設定
  validates :content, presence: true, unless: :was_attached?

  # was_attached?  画像があればtrue、なければfalseを返す仕組み
  def was_attached?
    self.image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  # Room（親モデル）が削除されたときに、関連付けしているRoomUser（子モデル）は削除
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  # 1つのチャットルームに、メッセージは複数存在
  # Room（親モデル）が削除されたときに、関連付けしているMessage（子モデル）は削除
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # 空の場合はDBに保存しないというバリデーションを設定
  validates :name, presence: true  
  
  has_many :room_users
  has_many :rooms, through: :room_users
  # 1人のユーザーは、複数のメッセージを送信
  has_many :messages  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # 定義されたconfigure_permitted_parametersが実行 定義しないと以下内容が読み込まれない
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  # 初期設定の段階では、メールアドレスとパスワードのみを受け取るように設定している。
  # 新しいキーをコントローラに追加するために、ストロングパラメーターを編集
  # nameの追加
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    # Message.newで生成した、Messageモデルのインスタンス情報を代入
    @message = Message.new
    # Room.find(params[:room_id])と記述することで、paramsに含まれているroom_idを代入
    # ルーティングをネストしているため/rooms/:room_id/messagesといったパスになる。
    # パスにroom_idが含まれているため、paramsというハッシュオブジェクトの中に、room_idという値が存在。
    # →そのため、params[:room_id]と記述することでroom_idを取得。
    @room = Room.find(params[:room_id]) 
    # チャットルームに紐付いている全てのメッセージ（@room.messages）を@messagesと定義
    # 一覧画面で表示するメッセージ情報には、ユーザー情報も紐付いて表示
    # includes(:user)と記述、ユーザー情報を1度のアクセスでまとめて取得（N+1問題の解消）
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    # @room.messages.newでチャットルームに紐づいたメッセージのインスタンスを生成し、message_paramsを引数にして、privateメソッドを呼び出し    
    # 生成したインスタンスを@messageに代入
    @message = @room.messages.new(message_params)
    # saveメソッドでメッセージの内容をmessagesテーブルに保存
    if @message.save
      # 成功：redirect_toメソッドを用いてmessagesコントローラーのindexアクションに再度リクエストを送信し、新たにインスタンス変数を生成
      redirect_to room_messages_path(@room)
    else
      # 投稿に失敗したときの処理にも、同様に@messagesを定義
      # @messageの情報を保持しつつindex.html.erbを参照可能
      @messages = @room.messages.includes(:user)
      # 失敗：renderメソッドを用いてindexアクションのindex.html.erbを表示するように指定。
      # このとき、indexアクションのインスタンス変数はそのままindex.html.erbに渡され、同じページに戻る
      render :index
    end
  end

  private
  # message_paramsを定義し、メッセージの内容contentをmessagesテーブルへ保存
  # パラメーターの中に、ログインしているユーザーのidと紐付いている、メッセージの内容contentと画像imageを受け取れるように許可
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end
  
  # チャットルームの新規作成のため「new」アクションを定義。
  # form_withに渡す引数として、値が空のRoomインスタンスを@roomに代入。
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    # createアクション内の記述も保存の成功・失敗による条件分岐が必要
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    # Room.find(params[:id])を使用して、削除したいチャットルームの情報を取得
    room = Room.find(params[:id])
    # インスタンス変数ではなく変数としてroomを定義し、destroyメソッドを使用
    room.destroy
    # root（roomsのindex）にリダイレクトする記述
    redirect_to root_path
  end

  private

  def room_params
    # 配列に対して保存を許可したい場合は、キーに対し[]を値として記述
    params.require(:room).permit(:name, user_ids: [])
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end  

  def update
    if current_user.update(user_params)
      # 成功した場合、root（チャット画面）にリダイレクト
      redirect_to root_path
    else
      # 失敗した場合、editのアクションを指定→editのビューが表示されます。
      render :edit
    end  
  end
  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# リセットCSSを指定 %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%# チャットルーム名の情報を取得。※すでにコントローラーの@roomで取得 %>
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%# 削除のパスはroom_path %>
      <%# 削除するチャットルームを区別するために、定義している@roomを引数にし、room_path(@room)と指定 %>
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%# _message.html.erbを部分テンプレートとして、読み込むことが可能 %>
  <%= render partial: 'message', collection: @messages %>
</div>

<%# form_withの引数に@room, @message %>
<%# →messagesのルーティングがroomsにネストされているため %>
<%# form_withのmodelオプションに記述した@roomには「指定のチャットルームのレコード情報」、@messageには「Messageモデルのからのインスタンス（Message.new）」をあらかじめセットしておく必要がある %>
<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%# messagesテーブルのuser_idに紐付いているユーザー名を、user.nameと記述することで取得 %>
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>      
      <%# messagesテーブルのcreated_atカラムから、投稿した時刻を取得 %>
      <%= message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%# messagesテーブルのcontentカラムから、メッセージの内容を取得 %>
      <%= message.content %>
    </div>
    <%# image_tagメソッドを記述して、画像を表示 %>
    <%# 要素の生成に条件をつけ、attached?メソッドで画像の添付をチェック %>
    <%# variantメソッドを使用することで、ファイルの表示サイズを指定 %>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%#  ログインしているユーザーの編集をするため 、edit_user_path(current_user)と指定%>
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

<div class="rooms">
<%# 「チャットルーム名を表示する」という処理を繰り返し実行 %>
<%# 「|room|」の部分は変数名なので命名規則はないですが、今回は分かりやすいように「room」 %>
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
      <%# room.nameの「name」は、roomsテーブルのカラム名 %>
      <%# パスにroomを引数とすることで、メッセージと紐付いているチャットルームのidを持たせることが可能 %>
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<%# サイドバーとチャット画面の部分テンプレートを読み込む ※ファイル名先頭の「_」や拡張子は必要無し%>
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar"%>
  </div>
  
  <div class="chat">
    <%= render "main_chat"%>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <%# プルダウンの実装 %>
        <%# # room[user_ids][]で送られるパラメーター %>
        <%# {"room" => {"user_ids" => ["選択したユーザーのid"]}}   %>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <%# 現在ログインしているユーザーをeachメソッドの処理から取り除く %>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <%# type属性にhiddenを指定することで、画面上には表示されないinput要素を作成 %>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%# HTTPメソッドのdeleteを指定すると、ログイン時に使用されるdeviseのsessionsコントローラーのdestroyアクションが実行 %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>